"""Prospective logical-only generator; currently exposed for disjoint calibration.

No formal seed inventory or formal execution entry point is defined here. HE and
mask randomness remain entirely separate from these public synthetic workloads.
"""

from __future__ import annotations

import hashlib
import random
from itertools import permutations

from dynamic_cssc.events import NetUpdate
from dynamic_cssc.r1_native_lifecycle import STRATEGIES, Workload, canonical

COLS = 8193
WINDOWS = 8
NONZERO_VALUES = tuple(value for value in range(-7, 8) if value)
CALIBRATION_DOMAIN = "engineering-disjoint-r1-calibration-20261005-v1"


def _rng(identity: str, *domain: object) -> random.Random:
    seed = int.from_bytes(hashlib.sha256(canonical((identity, *domain))).digest(), "big")
    return random.Random(seed)


def _generate(*, rows: int, distribution: str, queries_per_window: int, identity: str) -> Workload:
    if type(rows) is not int or rows not in {256, 1024}:
        raise ValueError("rows must be 256 or 1024")
    if distribution not in {"concentrated", "dispersed"}:
        raise ValueError("unsupported update distribution")
    if type(queries_per_window) is not int or queries_per_window not in {1, 8}:
        raise ValueError("queries per window must be 1 or 8")
    if not identity.startswith("engineering-disjoint-"):
        raise ValueError("no formal inputs may be generated by this unfrozen interface")

    initial_rng = _rng(identity, "initial", rows)
    logical = {}
    for row in range(rows):
        for column in sorted(initial_rng.sample(range(COLS), 8)):
            logical[row, column] = initial_rng.choice(NONZERO_VALUES)
    initial = tuple((row, column, value) for (row, column), value in sorted(logical.items()))
    updates_rng = _rng(identity, "updates", rows, distribution)
    domain_rows = rows // 16 if distribution == "concentrated" else rows
    edits_per_kind = rows // 32
    windows, queries = [], []
    for window in range(WINDOWS):
        # This function imports no strategy implementation and never observes
        # overflow, physical layout, performance, or which strategy will run.
        eligible = sorted(key for key in logical if key[0] < domain_rows)
        selected = updates_rng.sample(eligible, 2 * edits_per_kind)
        touched = set(selected)
        updates = []
        for row, column in selected[:edits_per_kind]:
            before = logical[row, column]
            after = updates_rng.choice(tuple(value for value in NONZERO_VALUES if value != before))
            updates.append(NetUpdate(row, column, before, after))
        for row, column in selected[edits_per_kind:]:
            updates.append(NetUpdate(row, column, logical[row, column], 0))
        while len(updates) < 4 * edits_per_kind:
            coordinate = updates_rng.randrange(domain_rows), updates_rng.randrange(COLS)
            if coordinate in logical or coordinate in touched:
                continue  # Reject only logical illegality, never strategy behavior.
            touched.add(coordinate)
            updates.append(NetUpdate(*coordinate, 0, updates_rng.choice(NONZERO_VALUES)))
        updates.sort(key=lambda update: (update.row, update.col))
        windows.append(tuple(updates))
        for update in updates:
            if update.after:
                logical[update.row, update.col] = update.after
            else:
                del logical[update.row, update.col]
        window_queries = []
        for query in range(queries_per_window):
            # Independent indexed domains, not the first h*8 items of one stream.
            query_rng = _rng(identity, "query", rows, window, query)
            window_queries.append(tuple(query_rng.randint(-7, 7) for _ in range(COLS)))
        queries.append(tuple(window_queries))
    result = Workload(
        f"{identity}-r{rows}-{distribution}-h{queries_per_window}",
        rows,
        COLS,
        initial,
        tuple(windows),
        tuple(queries),
    )
    result.validate()
    return result


def calibration_workload(*, rows: int, distribution: str, queries_per_window: int) -> Workload:
    """Single fixed disjoint input domain; not a selectable seed search."""
    return _generate(
        rows=rows,
        distribution=distribution,
        queries_per_window=queries_per_window,
        identity=CALIBRATION_DOMAIN,
    )


def balanced_strategy_order(group: int, repetition: int) -> tuple[str, ...]:
    """Six orders used exactly twelve times over 24 groups x 3 repeats."""
    if type(group) is not int or not 0 <= group < 24:
        raise ValueError("group must be 0..23")
    if type(repetition) is not int or not 0 <= repetition < 3:
        raise ValueError("repetition must be 0..2")
    return tuple(permutations(STRATEGIES))[(group + repetition) % 6]
